import type { Metadata } from "next";
import "./globals.css";
import HeaderBar from "@/components/menu";
import { CartProvider } from "@/context/cartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <HeaderBar />
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
